// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  commonSidebar: [{type: 'autogenerated', dirName: 'common'}],
  posSidebar: [{type: 'autogenerated', dirName: 'pos'}],
  inventorySidebar: [{type: 'autogenerated', dirName: 'inventory'}],
  salesSidebar: [{type: 'autogenerated', dirName: 'sales'}],
  orderSidebar: [{type: 'autogenerated', dirName: 'order'}],
  reportSidebar: [{type: 'autogenerated', dirName: 'report'}],
  storeManagementSidebar: [{type: 'autogenerated', dirName: 'store-management'}],
  systemSettingSidebar: [{type: 'autogenerated', dirName: 'system-setting'}],
  lmsSidebar: [{type: 'autogenerated', dirName: 'lms'}],
};

export default sidebars;
